# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_heat <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5) {
    .Call('_heateq_c_heat', PACKAGE = 'heateq', n, init, boundary, alpha, dt, eps)
}

c_heat_memory <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5) {
    .Call('_heateq_c_heat_memory', PACKAGE = 'heateq', n, init, boundary, alpha, dt, eps)
}

