# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
c_heat_neumann <- function(n, soln, alpha, eps, dt, space) {
    .Call('_heateq_c_heat_neumann', PACKAGE = 'heateq', n, soln, alpha, eps, dt, space)
}

#' @export
c_heat_dirichlet <- function(n, soln, alpha, eps, dt, space) {
    .Call('_heateq_c_heat_dirichlet', PACKAGE = 'heateq', n, soln, alpha, eps, dt, space)
}

#' @export
c_heat <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5) {
    .Call('_heateq_c_heat', PACKAGE = 'heateq', n, init, boundary, alpha, dt, eps)
}

#' @export
NULL

#' @export
c_heat_dirichlet_memory <- function(n, init, alpha, eps, dt, space) {
    .Call('_heateq_c_heat_dirichlet_memory', PACKAGE = 'heateq', n, init, alpha, eps, dt, space)
}

#' @export
c_heat_neumann_memory <- function(n, init, alpha, eps, dt, space) {
    .Call('_heateq_c_heat_neumann_memory', PACKAGE = 'heateq', n, init, alpha, eps, dt, space)
}

c_heat_memory <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5) {
    .Call('_heateq_c_heat_memory', PACKAGE = 'heateq', n, init, boundary, alpha, dt, eps)
}

