# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_heat_neumann <- function(n, soln, alpha, eps, dt, space, dx) {
    .Call(`_heateq_c_heat_neumann`, n, soln, alpha, eps, dt, space, dx)
}

c_heat_dirichlet <- function(n, soln, alpha, eps, dt, space, dx) {
    .Call(`_heateq_c_heat_dirichlet`, n, soln, alpha, eps, dt, space, dx)
}

c_heat <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5, dx = 0.1) {
    .Call(`_heateq_c_heat`, n, init, boundary, alpha, dt, eps, dx)
}

c_heat_dirichlet_memory <- function(n, init, alpha, eps, dt, space, dx) {
    .Call(`_heateq_c_heat_dirichlet_memory`, n, init, alpha, eps, dt, space, dx)
}

c_heat_neumann_memory <- function(n, init, alpha, eps, dt, space, dx) {
    .Call(`_heateq_c_heat_neumann_memory`, n, init, alpha, eps, dt, space, dx)
}

c_heat_memory <- function(n, init, boundary, alpha, dt = 0.1, eps = 1e-5, dx = 0.1) {
    .Call(`_heateq_c_heat_memory`, n, init, boundary, alpha, dt, eps, dx)
}

